{ "level": "ERROR", "date": "2020-06-22 15:17:20.9945", "logger": "Kay.Boilerplate.ApplicationService.AppService.UserAppService", "callsite": "Kay.Boilerplate.ApplicationService.AppService.UserAppService.GetByUserName", "linenumber": "34", "message": "用户名不能为空" }
{ "level": "ERROR", "date": "2020-06-22 15:17:23.2522", "logger": "Kay.Framework.AspNetCore.Exceptions.ExceptionMiddleware", "callsite": "Kay.Framework.Logging.LoggerExtensions.LogWithLevel", "linenumber": "44", "message": "{\"data\":{\"errorCode\":\"InternalServerError\",\"errorMessage\":\"用户名不能为空\",\"errorDetails\":null,\"validationErrors\":null},\"code\":1,\"msg\":\"用户名不能为空\",\"serverTime\":637284358430666011}", "exception": "System.ComponentModel.DataAnnotations.ValidationException: 用户名不能为空\r\n   at Kay.Boilerplate.ApplicationService.AppService.UserAppService.GetByUserName(String userName) in C:\\Users\\zhengweilin\\Desktop\\core\\Kay.Framework\\Kay.Boilerplate.ApplicationService\\AppService\\UserAppService.cs:line 38\r\n   at Kay.Boilerplate.Application.Service.Http.Controllers.UserController.GetByUserName(String userName) in C:\\Users\\zhengweilin\\Desktop\\core\\Kay.Framework\\Kay.Boilerplate.Application.Service.Http\\Controllers\\UserController.cs:line 29\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n   at Kay.Framework.AspNetCore.Exceptions.ExceptionMiddleware.Invoke(HttpContext context) in C:\\Users\\zhengweilin\\Desktop\\core\\Kay.Framework\\Kay.Framework.AspNetCore\\Exceptions\\ExceptionMiddleware.cs:line 39" }
